name = "geo-header-worker"
main = "src/index.ts"
compatibility_date = "2025-03-07"

# Development environment
[env.dev]
vars = { ALLOWED_ORIGINS = "*" }
route = "*.test.dev.xyz/geo"

# Production environment
[env.prod]
vars = { ALLOWED_ORIGINS = "https://frontend.xyz,https://*.preview.frontend.xyz" }
route = "test.xyz/geo"
